# Generated by Django 4.0.5 on 2023-07-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v6', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_model',
        ),
    ]
