"""
Django settings for mystifly_api project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from opencensus.trace import config_integration


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y%!p&w*s$%mkx7=ney!8)$59ovy8ecx@c(47^f7e#tm%pn347j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'v1.ryanair',
    'account',
    'django_crontab',
    'custom_logger',
    'v6',
    'easyjet'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'opencensus.ext.django.middleware.OpencensusMiddleware',
]

ROOT_URLCONF = 'mystifly_api.urls'
AUTH_USER_MODEL = 'account.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mystifly_api.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'screen_short/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


IS_PRODUCTION = False

if IS_PRODUCTION:
#     Driver Info
    CHROME_DRIVER_LOCATION = "/app/artifacts/chromedriver"
    CHROME_BINARY_LOCATION = "/usr/bin/google-chrome"

    #production_db
    DATABASE_ENGINE = 'django.db.backends.postgresql'
    DATABASE_NAME = 'supplierintegration'
    DATABASE_USERNAME = 'postgres'
    DATABASE_PASSWORD = 'root'
    DATABASE_HOST = '10.112.64.4'
    DATABASE_PORT = '5432'
    
    #driver
    IS_HEADLESS_DRIVER = True
    #either of these two proxy should be enabled
    USE_PACKETSTREAM_PROXY = True
    USE_TTPROXY = True
    IS_LOG_ENABLED = True
    IS_KIBANA_ENABLED = True

else:

    # #Raju Driver
    # CHROME_DRIVER_LOCATION =  "D:\chromedriver.exe"
    # CHROME_BINARY_LOCATION = "C:\Program Files\Google\Chrome\Application\chrome.exe"
    
    #staging_db
    DATABASE_ENGINE = 'django.db.backends.postgresql'
    DATABASE_NAME = 'supplierIntegration'
    DATABASE_USERNAME = 'postgres'
    DATABASE_PASSWORD = 'root'
    DATABASE_HOST = '192.168.1.176'
    DATABASE_PORT = '5432'
    
    IS_HEADLESS_DRIVER = False
    
    #either of these two proxy should be enabled
    USE_PACKETSTREAM_PROXY = True
    USE_TTPROXY = True

#Maheswaran local driver dev
    CHROME_DRIVER_LOCATION = "/home/maheswaran/chromedriver"
    CHROME_BINARY_LOCATION = "/usr/bin/google-chrome"

    IS_LOG_ENABLED = True
    IS_KIBANA_ENABLED = False



TOKEN_EXPIRED_AFTER_SECONDS = 7200

CRONJOBS = [
    ('*/4 * * * *', 'v1.ryanair.tasks.close_unused_webdriver'),
    ('* */4 * * *', 'utils.proxy_scheduler.get_proxy'),
    ('*/30 * * * *', 'v1.ryanair.tasks.check_journey_time_for_alert')
]

ELASTIC_SEARCH_HOST = os.environ.get("ELASTIC_SEARCH_HOST", "10.1.0.145:9200")
ELASTIC_SEARCH_USER = os.environ.get("ELASTIC_SEARCH_USER", "")
ELASTIC_SEARCH_PASS = os.environ.get("ELASTIC_SEARCH_PASS", "")
ELASTIC_SEARCH_INDEX = os.environ.get("ELASTIC_SEARCH_INDEX", "supplierintegration")
STORAGE_ACCOUNT = os.environ.get("STORAGE_ACCOUNT", "ryanair")
ACCOUNT_KEY = os.environ.get("ACCOUNT_KEY", "QCYLS9nMgozjpqOS0BaE8IFKN5TJOEekJh5TGwj8t0YFJbfvmGnPSROopk+W0mqRU6Xy8kn0Xpvf+ASt9/axQg==")
CONNECTION_STRING = os.environ.get("CONNECTION_STRING", "DefaultEndpointsProtocol=https;AccountName=ryanair;AccountKey=QCYLS9nMgozjpqOS0BaE8IFKN5TJOEekJh5TGwj8t0YFJbfvmGnPSROopk+W0mqRU6Xy8kn0Xpvf+ASt9/axQg==")
CONTAINER = os.environ.get("CONTAINER", "ryanair-container")
DJANGO_ENVIRONMENT_NAME = 'mystifly_api.settings'

#local
# DATABASE_ENGINE = 'django.db.backends.postgresql'
# DATABASE_NAME = 'supplierIntegration'
# DATABASE_USERNAME = 'postgres'
# DATABASE_PASSWORD = '0800'
# DATABASE_HOST = '127.0.0.1'
# DATABASE_PORT = '5432'


DATABASES = {
    'default': {

        'NAME': DATABASE_NAME,
        'ENGINE': DATABASE_ENGINE,
        'USER': DATABASE_USERNAME,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT
    }
}



# Proxy settings
PROXY_HOST = "proxy.packetstream.io"
PROXY_PORT = 31112
PROXY_USERNAME = "sahil1021"
PROXY_PASSWORD = "bzCbamCGzVll1edv"

PROXYDICT = {
    'http': 'http://sahil1021:bzCbamCGzVll1edv@proxy.packetstream.io:31112',
    'https': 'http://sahil1021:bzCbamCGzVll1edv@proxy.packetstream.io:31112',
}
#dev redis ("10.10.0.4", 6379)
REDIS_CLUSTER_NODES = [{"host": "10.112.0.43", "port": "6379"},{"host": "10.112.0.38", "port": "6379"},{"host": "10.112.0.40", "port": "6379"}]
OPENCENSUS = {
    'TRACE': {
        'SAMPLER': 'opencensus.trace.samplers.ProbabilitySampler(rate=0.5)',
        'EXPORTER': '''opencensus.ext.azure.trace_exporter.AzureExporter(
            connection_string="InstrumentationKey=cd29da66-1f95-4220-82d2-08f2454321a9;IngestionEndpoint=https://southcentralus-3.in.applicationinsights.azure.com/;LiveEndpoint=https://southcentralus.livediagnostics.monitor.azure.com/"
        )''',
        'EXCLUDELIST_PATHS': [],
    }
}

config_integration.trace_integrations(['postgresql'])

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'custom_logger.custom_handler.ElasticSearchLogHandler',
        },
        'azure': {
                    "level": "DEBUG",
                    "class": "opencensus.ext.azure.log_exporter.AzureLogHandler",
                    "connection_string": "InstrumentationKey=cd29da66-1f95-4220-82d2-08f2454321a9;IngestionEndpoint=https://southcentralus-3.in.applicationinsights.azure.com/;LiveEndpoint=https://southcentralus.livediagnostics.monitor.azure.com/",
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ["file", "azure"],
            'level': 'ERROR',
            'propagate': True,
        },
        'v1': {
            'handlers': ["file", "azure"],
            'level': 'ERROR',
            'propagate': True,
        },
        'v2': {
            'handlers': ["file", "azure"],
            'level': 'ERROR',
            'propagate': True,
        },
        'utils': {
            'handlers': ["file", "azure"],
            'level': 'ERROR',
            'propagate': True,
        },
        'easyjet': {
            'handlers': ["file", "azure"],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}



