# Generated by Django 4.0.5 on 2023-02-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ryanair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='near_by_airports',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ryanair.country'),
        ),
    ]
