# Generated by Django 4.0.5 on 2023-08-16 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ryanair', '0002_airport_near_by_airports_alter_airport_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='mapping_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Airport_New',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('near_by_airports', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=255, null=True)),
                ('mapping_code', models.CharField(max_length=255, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ryanair.country')),
            ],
            options={
                'get_latest_by': 'updated_on',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
