# Generated by Django 4.0.5 on 2023-08-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ryanair', '0003_airport_mapping_code_airport_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='mapping_code',
        ),
    ]
