# Generated by Django 4.0.5 on 2023-08-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryanair', '0004_remove_airport_mapping_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='mapping_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Airport_New',
        ),
    ]
