COOKIES ={'sahilkanger21@gmail.com': [{'domain': '.ryanair.com', 'expiry': 1660159461, 'httpOnly': False, 'name': 'myRyanairID', 'path': '/',
            'secure': True, 'value': '13u01nhq54e60'},
           {'domain': '.ryanair.com', 'expiry': 1691693627, 'httpOnly': False,
            'name': 'bid_FRwdAp7a9G2cnLnTsgyBNeduseKcPcRy', 'path': '/', 'sameSite': 'None', 'secure': True,
            'value': '87f4a74c-c1b7-45fb-b049-275b6edd471d'},
           {'domain': 'www.ryanair.com', 'expiry': 1660157747, 'httpOnly': False, 'name': '_hjIncludedInSessionSample',
            'path': '/', 'sameSite': 'Lax', 'secure': True, 'value': '0'},
           {'domain': '.ryanair.com', 'expiry': 1691693627, 'httpOnly': False, 'name': '_hjSessionUser_135144',
            'path': '/', 'sameSite': 'Lax', 'secure': True,
            'value': 'eyJpZCI6IjA4MGE5NTZhLTI1ZDgtNTkwYi1iMTRhLTZkZDZkNWZjMTUzZiIsImNyZWF0ZWQiOjE2NjAxNTc2MjczNDEsImV4aXN0aW5nIjpmYWxzZX0='},
           {'domain': '.ryanair.com', 'expiry': 1660159457, 'httpOnly': False, 'name': '_hjSession_135144', 'path': '/',
            'sameSite': 'Lax', 'secure': True,
            'value': 'eyJpZCI6ImM1YzU0MzQ3LWViMjctNGU0Mi05YzVhLTUzMjM5MGJlNWI0NiIsImNyZWF0ZWQiOjE2NjAxNTc2MjczNTQsImluU2FtcGxlIjpmYWxzZX0='},
           {'domain': '.www.ryanair.com', 'expiry': 1676055226, 'httpOnly': False, 'name': 'RY_COOKIE_CONSENT',
            'path': '/', 'secure': False, 'value': 'true'},
           {'domain': '.www.ryanair.com', 'expiry': 1676055226, 'httpOnly': False, 'name': 'STORAGE_PREFERENCES',
            'path': '/', 'secure': False,
            'value': '{"STRICTLY_NECESSARY":true,"PERFORMANCE":true,"FUNCTIONAL":true,"TARGETING":true,"SOCIAL_MEDIA":true,"PIXEL":true,"GANALYTICS":true,"__VERSION":2}'},
           {'domain': '.ryanair.com', 'expiry': 1660244026, 'httpOnly': False, 'name': '_gid', 'path': '/',
            'secure': False, 'value': 'GA1.2.1949035699.1660157626'},
           {'domain': '.ryanair.com', 'httpOnly': True, 'name': 'agsy', 'path': '/', 'secure': False,
            'value': 'AdhGoEQBAAu7CKcBe9pI8cO6JQ..'},
           {'domain': '.ryanair.com', 'httpOnly': True, 'name': 'agsn', 'path': '/', 'secure': False,
            'value': '3GUz6bmh93agDEYcB4_X4wbKaglD7QkC0tu7HNDZVag.'},
           {'domain': '.ryanair.com', 'expiry': 1660157686, 'httpOnly': False, 'name': '_gat_gtag_UA_153938230_2',
            'path': '/', 'secure': False, 'value': '1'},
           {'domain': '.ryanair.com', 'expiry': 1691693625, 'httpOnly': False, 'name': 'mkt', 'path': '/',
            'secure': True, 'value': '/gb/en/'},
           {'domain': '.ryanair.com', 'httpOnly': True, 'name': 'agso', 'path': '/', 'secure': False,
            'value': 'Afvtuo4BAAu7CKcBe9pISp5iUQRFs5M.'},
           {'domain': '.ryanair.com', 'expiry': 1691625600, 'httpOnly': True, 'name': 'rid.sig', 'path': '/',
            'secure': True,
            'value': 'OCBtG/WF9HO7H4S44kdr0UbtcRDoPHA2FlZPzHW23p9R69K+AwWuDuCc7vYSnPSCK8vNuhXGxPc1oKwQT1HrFhu7W7HzxINcSGSaGoFXje01KeNfA+QcI4CM6rEbydaZpA9bYuAiv7nGWudB5PuReF7mDYoxwRegr2PF/CLdgo1Kk1NMRZUK4jF5SSvuQJYHnWmcFuxIoGEoAzD9jydct/oV/W7Ip04AWj5wy/OJHrTWqciT3xAHxW7GhTTR3KRm/uDfN9d1Sum3oCRwRH+/qfjrD5NyVN7wBwyMR00ZnRY='},
           {'domain': '.ryanair.com', 'httpOnly': True, 'name': 'RYANSESSION', 'path': '/', 'secure': True,
            'value': 'YvP@uQqhAm0AABJU0m4AAAAo'},
           {'domain': '.ryanair.com', 'expiry': 1660159457, 'httpOnly': False, 'name': '_hjAbsoluteSessionInProgress',
            'path': '/', 'sameSite': 'Lax', 'secure': True, 'value': '0'},
           {'domain': '.ryanair.com', 'expiry': 1660159457, 'httpOnly': False, 'name': '_hjFirstSeen', 'path': '/',
            'sameSite': 'Lax', 'secure': True, 'value': '1'},
           {'domain': '.ryanair.com', 'httpOnly': False, 'name': 'fr-correlation-id', 'path': '/', 'secure': True,
            'value': 'a922acc4-5be9-4f5a-8506-9217c0241b05'},
           {'domain': '.ryanair.com', 'expiry': 1723229626, 'httpOnly': False, 'name': '_ga', 'path': '/',
            'secure': False, 'value': 'GA1.2.959342970.1660157626'},
           {'domain': '.ryanair.com', 'expiry': 1691693625, 'httpOnly': True, 'name': 'agsd', 'path': '/',
            'secure': False, 'value': '8n8OlKV_6u5bhOSV3wHxLbqNVT6RwFdntqAXMUun8XPBYY_-'},
           {'domain': '.ryanair.com', 'expiry': 1691625600, 'httpOnly': True, 'name': 'rid', 'path': '/',
            'secure': True, 'value': '23e6fdb0-7b32-4133-8c22-e90f9a661026'}]

           }
