# Generated by Django 4.0.5 on 2023-08-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('is_deleted', models.BooleanField(default=False)),
                ('client_code', models.CharField(max_length=50)),
                ('is_client_enabled', models.BooleanField(default=False)),
                ('is_operations_enabled', models.BooleanField(default=False)),
                ('service_type', models.CharField(max_length=50)),
            ],
            options={
                'get_latest_by': 'updated_on',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='client_emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('is_deleted', models.BooleanField(default=False)),
                ('client_code', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=255)),
            ],
            options={
                'get_latest_by': 'updated_on',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='operations_internal_emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('is_deleted', models.BooleanField(default=False)),
                ('email_id', models.EmailField(max_length=255)),
                ('is_ryanair_enabled', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'updated_on',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
