# Generated by Django 4.0.5 on 2023-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_logger', '0002_client_config_client_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert_schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('is_deleted', models.BooleanField(default=False)),
                ('journey_start', models.DateTimeField()),
                ('timezone', models.CharField(max_length=100)),
                ('pnr', models.CharField(max_length=20)),
                ('email_used', models.EmailField(max_length=255)),
                ('client_code', models.CharField(max_length=20)),
            ],
            options={
                'get_latest_by': 'updated_on',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
