# Generated by Django 4.0.5 on 2023-08-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyjet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nearby_airports',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.EmailField(max_length=254)),
                ('updated_by', models.EmailField(max_length=254)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('airport_code', models.CharField(max_length=255)),
                ('mapping_airport_code', models.CharField(max_length=255)),
                ('meta_data', models.JSONField()),
            ],
            options={
                'get_latest_by': 'updated_on',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
